name: netsim
version: 0.0.0.0
ghc-options: -Wall -fwarn-tabs -fwarn-incomplete-record-updates -fwarn-monomorphism-restriction -fwarn-unused-do-bind
dependencies:
  - base
  - containers
  - brick
  - vty
  - microlens
  - microlens-th
  - microlens-mtl
  - mtl
  - socket
  - bytestring

library:
  exposed-modules: NetSim.Core
  source-dirs: src
